### ISSUE TITLE
Plugin throws if onRequest handler didn't get a chance to run

### ISSUE THREAD

**Issue by hassy** [cjihrig/server-timi#1]
First off, thanks for the plugin @cjihrig! An issue we've run into (which admittedly is an issue in our codebase as well!) is that if the `onRequest` handler didn't get a chance to run (i.e. when a plugin that gets initialized *before* `server-timi` throws for whatever reason), then `onPreResponse` will always throw on this line: https://github.com/cjihrig/server-timi/blob/master/lib/index.js#L64

Happy to send a PR with a fix, just let me know.

**Comment by cjihrig** [comment]
Thanks @hassy. A PR is welcome!
